-- Seed default policy templates for the policy library
INSERT OR IGNORE INTO policy_library (id, title, category, description, content_text, version, review_cycle_days, created_at, updated_at) VALUES
  ('pl_info_sec', 'Information Security Policy', 'security', 'Establishes the framework for managing information security across the organization.', 'This policy defines the organization''s approach to information security, including asset management, access control, cryptography, physical security, operations security, and communications security. All employees and contractors must comply with this policy.', '1.0', 365, datetime('now'), datetime('now')),
  ('pl_access_ctrl', 'Access Control Policy', 'access', 'Defines requirements for granting, reviewing, and revoking access to systems and data.', 'This policy governs how access to information systems is managed. It covers user registration, privilege management, authentication requirements, access reviews, and the principle of least privilege. Access must be approved by system owners and reviewed quarterly.', '1.0', 90, datetime('now'), datetime('now')),
  ('pl_data_class', 'Data Classification Policy', 'security', 'Defines how data is classified, labeled, and handled based on sensitivity.', 'All organizational data must be classified as Public, Internal, Confidential, or Restricted. Each classification level has specific handling, storage, transmission, and disposal requirements. Data owners are responsible for assigning classifications.', '1.0', 365, datetime('now'), datetime('now')),
  ('pl_privacy', 'Privacy Policy', 'privacy', 'Describes how personal data is collected, processed, stored, and protected.', 'This policy ensures compliance with applicable privacy regulations (GDPR, CCPA, etc.). It covers data collection principles, consent management, data subject rights, data retention, cross-border transfers, and breach notification procedures.', '1.0', 365, datetime('now'), datetime('now')),
  ('pl_incident', 'Incident Response Policy', 'incident', 'Outlines procedures for detecting, responding to, and recovering from security incidents.', 'This policy establishes the incident response team, defines incident severity levels, and outlines the phases of incident response: preparation, identification, containment, eradication, recovery, and lessons learned. All incidents must be documented and reported within defined timeframes.', '1.0', 180, datetime('now'), datetime('now')),
  ('pl_acceptable_use', 'Acceptable Use Policy', 'security', 'Defines acceptable and prohibited uses of organizational IT resources.', 'This policy covers the acceptable use of company devices, networks, email, internet, and cloud services. It addresses personal use, prohibited activities, monitoring, and consequences of policy violations. All users must acknowledge this policy upon onboarding.', '1.0', 365, datetime('now'), datetime('now')),
  ('pl_password', 'Password and Authentication Policy', 'access', 'Establishes requirements for passwords, MFA, and authentication mechanisms.', 'Passwords must meet minimum complexity requirements (12+ characters, mixed case, numbers, symbols). Multi-factor authentication is required for all critical systems. Password reuse is prohibited. Service accounts must use API keys or certificates instead of passwords.', '1.0', 180, datetime('now'), datetime('now')),
  ('pl_change_mgmt', 'Change Management Policy', 'security', 'Defines processes for requesting, approving, and implementing changes to IT systems.', 'All changes to production systems must follow the change management process: request, review, approve, implement, and verify. Emergency changes require post-implementation review. Changes must be documented with rollback plans.', '1.0', 365, datetime('now'), datetime('now')),
  ('pl_vendor', 'Vendor and Third-Party Risk Policy', 'security', 'Governs the assessment and management of risks from third-party vendors.', 'All vendors with access to organizational data or systems must undergo security assessment before onboarding. Vendors are classified by risk tier and reviewed accordingly. Contracts must include security requirements, data handling clauses, and right to audit.', '1.0', 365, datetime('now'), datetime('now')),
  ('pl_bcdr', 'Business Continuity and Disaster Recovery Policy', 'incident', 'Ensures organizational resilience through continuity planning and disaster recovery.', 'This policy requires business impact analysis, recovery time objectives (RTO), recovery point objectives (RPO), and regular testing of continuity plans. Critical systems must have documented recovery procedures tested at least annually.', '1.0', 365, datetime('now'), datetime('now')),
  ('pl_hr_security', 'Human Resources Security Policy', 'hr', 'Addresses security aspects of the employee lifecycle from hiring to termination.', 'This policy covers background checks, security awareness training, acceptable use agreements, role-based access provisioning, and offboarding procedures including access revocation. All employees must complete annual security awareness training.', '1.0', 365, datetime('now'), datetime('now')),
  ('pl_encryption', 'Encryption and Key Management Policy', 'security', 'Defines requirements for encryption of data at rest and in transit.', 'All sensitive data must be encrypted at rest (AES-256) and in transit (TLS 1.2+). Encryption keys must be managed using approved key management systems with proper rotation schedules. Key custodians must be designated for all critical keys.', '1.0', 365, datetime('now'), datetime('now'));
