-- Restore all email templates to light theme:
-- dark header band (logo) + white body (dark text + green CTA button).
-- This matches the OTP style the user confirmed as correct.

UPDATE email_templates SET
  body_html = '<div style="background:#f4f4f5;padding:40px 20px;font-family:''Red Hat Display'',Arial,sans-serif;"><div style="max-width:480px;margin:0 auto;border-radius:16px;overflow:hidden;border:1px solid #e4e4e7;"><div style="background:#09090b;padding:24px 32px;text-align:center;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="28" /></div><div style="background:#ffffff;padding:36px 32px;"><h2 style="color:#09090b;font-size:20px;font-weight:700;margin:0 0 8px;">Verify your email</h2><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 24px;">Enter this code to sign in to Complerer:</p><div style="background:#f4f4f5;border:1px solid #e4e4e7;border-radius:12px;padding:24px;text-align:center;margin:0 0 24px;"><span style="font-size:36px;font-weight:700;letter-spacing:10px;color:#059669;">{{code}}</span></div><p style="color:#71717a;font-size:12px;line-height:1.6;margin:0 0 8px;">This code expires in 10 minutes.</p><p style="color:#71717a;font-size:12px;line-height:1.6;margin:0;">If you did not request this, please ignore this email.</p></div><div style="background:#fafafa;padding:16px 32px;border-top:1px solid #f4f4f5;text-align:center;"><p style="color:#a1a1aa;font-size:11px;margin:0;">Complerer · Compliance Platform</p></div></div></div>',
  variables = '["code"]',
  updated_at = datetime('now')
WHERE slug = 'otp-verification';

UPDATE email_templates SET
  body_html = '<div style="background:#f4f4f5;padding:40px 20px;font-family:''Red Hat Display'',Arial,sans-serif;"><div style="max-width:480px;margin:0 auto;border-radius:16px;overflow:hidden;border:1px solid #e4e4e7;"><div style="background:#09090b;padding:24px 32px;text-align:center;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="28" /></div><div style="background:#ffffff;padding:36px 32px;"><h2 style="color:#09090b;font-size:20px;font-weight:700;margin:0 0 8px;">You''ve been invited</h2><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 8px;">You''ve been invited to join <strong style="color:#09090b;">{{workspaceName}}</strong> on Complerer as a <strong style="color:#09090b;">{{role}}</strong>.</p><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 32px;">Sign in with this email address to accept and get started.</p><div style="text-align:center;margin:0 0 24px;"><a href="{{loginUrl}}" style="display:inline-block;background:#059669;color:#ffffff;font-weight:700;padding:14px 36px;border-radius:12px;text-decoration:none;font-size:14px;">Accept Invitation</a></div><p style="color:#a1a1aa;font-size:12px;text-align:center;margin:0;">This invitation expires in 7 days. If you did not expect this, you can ignore this email.</p></div><div style="background:#fafafa;padding:16px 32px;border-top:1px solid #f4f4f5;text-align:center;"><p style="color:#a1a1aa;font-size:11px;margin:0;">Complerer · Compliance Platform</p></div></div></div>',
  variables = '["workspaceName", "role", "loginUrl"]',
  updated_at = datetime('now')
WHERE slug = 'workspace-invitation';

UPDATE email_templates SET
  body_html = '<div style="background:#f4f4f5;padding:40px 20px;font-family:''Red Hat Display'',Arial,sans-serif;"><div style="max-width:480px;margin:0 auto;border-radius:16px;overflow:hidden;border:1px solid #e4e4e7;"><div style="background:#09090b;padding:24px 32px;text-align:center;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="28" /></div><div style="background:#ffffff;padding:36px 32px;"><h2 style="color:#09090b;font-size:20px;font-weight:700;margin:0 0 8px;">Welcome to {{workspaceName}}</h2><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 32px;">Your invitation request has been approved. You can now sign in and access the workspace.</p><div style="text-align:center;margin:0 0 8px;"><a href="{{loginUrl}}" style="display:inline-block;background:#059669;color:#ffffff;font-weight:700;padding:14px 36px;border-radius:12px;text-decoration:none;font-size:14px;">Sign In to Complerer</a></div></div><div style="background:#fafafa;padding:16px 32px;border-top:1px solid #f4f4f5;text-align:center;"><p style="color:#a1a1aa;font-size:11px;margin:0;">Complerer · Compliance Platform</p></div></div></div>',
  variables = '["workspaceName", "loginUrl"]',
  updated_at = datetime('now')
WHERE slug = 'invitation-approved';

UPDATE email_templates SET
  body_html = '<div style="background:#f4f4f5;padding:40px 20px;font-family:''Red Hat Display'',Arial,sans-serif;"><div style="max-width:480px;margin:0 auto;border-radius:16px;overflow:hidden;border:1px solid #e4e4e7;"><div style="background:#09090b;padding:24px 32px;text-align:center;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="28" /></div><div style="background:#ffffff;padding:36px 32px;"><h2 style="color:#09090b;font-size:20px;font-weight:700;margin:0 0 8px;">Request not approved</h2><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 12px;">Unfortunately, your request to join <strong style="color:#09090b;">{{workspaceName}}</strong> was not approved at this time.</p><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0;">Please contact a workspace administrator for more information.</p></div><div style="background:#fafafa;padding:16px 32px;border-top:1px solid #f4f4f5;text-align:center;"><p style="color:#a1a1aa;font-size:11px;margin:0;">Complerer · Compliance Platform</p></div></div></div>',
  variables = '["workspaceName"]',
  updated_at = datetime('now')
WHERE slug = 'invitation-rejected';

UPDATE email_templates SET
  body_html = '<div style="background:#f4f4f5;padding:40px 20px;font-family:''Red Hat Display'',Arial,sans-serif;"><div style="max-width:480px;margin:0 auto;border-radius:16px;overflow:hidden;border:1px solid #e4e4e7;"><div style="background:#09090b;padding:24px 32px;text-align:center;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="28" /></div><div style="background:#ffffff;padding:36px 32px;"><h2 style="color:#09090b;font-size:20px;font-weight:700;margin:0 0 8px;">New join request</h2><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 20px;"><strong style="color:#09090b;">{{userName}}</strong> wants to join <strong style="color:#09090b;">{{workspaceName}}</strong>.</p><div style="background:#f4f4f5;border:1px solid #e4e4e7;border-radius:10px;padding:14px 16px;margin:0 0 28px;"><p style="color:#71717a;font-size:11px;margin:0 0 4px;text-transform:uppercase;letter-spacing:0.5px;">Email</p><p style="color:#09090b;font-size:14px;font-weight:600;margin:0;">{{userEmail}}</p></div><div style="text-align:center;margin:0 0 8px;"><a href="{{settingsUrl}}" style="display:inline-block;background:#059669;color:#ffffff;font-weight:700;padding:14px 36px;border-radius:12px;text-decoration:none;font-size:14px;">Review Request</a></div></div><div style="background:#fafafa;padding:16px 32px;border-top:1px solid #f4f4f5;text-align:center;"><p style="color:#a1a1aa;font-size:11px;margin:0;">Complerer · Compliance Platform</p></div></div></div>',
  variables = '["userName", "userEmail", "workspaceName", "settingsUrl"]',
  updated_at = datetime('now')
WHERE slug = 'new-invitation-request';

UPDATE email_templates SET
  body_html = '<div style="background:#f4f4f5;padding:40px 20px;font-family:''Red Hat Display'',Arial,sans-serif;"><div style="max-width:480px;margin:0 auto;border-radius:16px;overflow:hidden;border:1px solid #e4e4e7;"><div style="background:#09090b;padding:24px 32px;text-align:center;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="28" /></div><div style="background:#ffffff;padding:36px 32px;"><h2 style="color:#09090b;font-size:20px;font-weight:700;margin:0 0 8px;">{{alertTitle}}</h2><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 20px;">{{alertMessage}}</p><div style="background:#f4f4f5;border:1px solid #e4e4e7;border-radius:10px;padding:14px 16px;margin:0 0 28px;"><p style="color:#71717a;font-size:11px;margin:0 0 6px;">Severity</p><p style="font-size:14px;font-weight:700;color:{{severityColor}};margin:0 0 10px;">{{severity}}</p><p style="color:#71717a;font-size:11px;margin:0 0 4px;">Framework</p><p style="color:#09090b;font-size:14px;margin:0;">{{framework}}</p></div><div style="text-align:center;margin:0 0 8px;"><a href="{{dashboardUrl}}" style="display:inline-block;background:#059669;color:#ffffff;font-weight:700;padding:14px 36px;border-radius:12px;text-decoration:none;font-size:14px;">View Dashboard</a></div></div><div style="background:#fafafa;padding:16px 32px;border-top:1px solid #f4f4f5;text-align:center;"><p style="color:#a1a1aa;font-size:11px;margin:0;">Complerer · Compliance Platform</p></div></div></div>',
  variables = '["alertTitle", "alertMessage", "severity", "severityColor", "framework", "dashboardUrl"]',
  updated_at = datetime('now')
WHERE slug = 'compliance-alert';

UPDATE email_templates SET
  body_html = '<div style="background:#f4f4f5;padding:40px 20px;font-family:''Red Hat Display'',Arial,sans-serif;"><div style="max-width:480px;margin:0 auto;border-radius:16px;overflow:hidden;border:1px solid #e4e4e7;"><div style="background:#09090b;padding:24px 32px;text-align:center;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="28" /></div><div style="background:#ffffff;padding:36px 32px;"><h2 style="color:#09090b;font-size:20px;font-weight:700;margin:0 0 8px;">Evidence expiring soon</h2><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 20px;">The following evidence will expire on <strong style="color:#09090b;">{{expiresAt}}</strong>:</p><div style="background:#f4f4f5;border:1px solid #e4e4e7;border-radius:10px;padding:14px 16px;margin:0 0 28px;"><p style="color:#09090b;font-weight:700;font-size:14px;margin:0 0 4px;">{{evidenceTitle}}</p><p style="color:#71717a;font-size:12px;margin:0;">Linked to {{controlCount}} controls</p></div><div style="text-align:center;margin:0 0 8px;"><a href="{{evidenceUrl}}" style="display:inline-block;background:#059669;color:#ffffff;font-weight:700;padding:14px 36px;border-radius:12px;text-decoration:none;font-size:14px;">Update Evidence</a></div></div><div style="background:#fafafa;padding:16px 32px;border-top:1px solid #f4f4f5;text-align:center;"><p style="color:#a1a1aa;font-size:11px;margin:0;">Complerer · Compliance Platform</p></div></div></div>',
  variables = '["evidenceTitle", "expiresAt", "controlCount", "evidenceUrl"]',
  updated_at = datetime('now')
WHERE slug = 'evidence-expiring';
