-- Fix Gmail dark mode: rebuild all email templates using table-based layout
-- with bgcolor HTML attributes + !important on background-color / color styles.
-- Gmail respects bgcolor attributes over dark-mode CSS overrides, preventing
-- the "white background with white text" issue seen in Gmail dark mode.

UPDATE email_templates SET
  body_html = '<table width="100%" cellpadding="0" cellspacing="0" bgcolor="#09090b" style="background-color:#09090b !important;"><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:40px 20px;font-family:''Red Hat Display'',Arial,sans-serif;"><table cellpadding="0" cellspacing="0" bgcolor="#09090b" style="width:100%;max-width:480px;background-color:#09090b !important;border-radius:16px;"><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:40px 32px 24px;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="28" /></td></tr><tr><td bgcolor="#09090b" style="background-color:#09090b !important;padding:0 32px;"><h2 style="color:#fafafa !important;font-size:20px;font-weight:700;margin:0 0 8px;">Verify your email</h2><p style="color:#a1a1aa !important;font-size:14px;line-height:1.6;margin:0 0 24px;">Enter this code to sign in to Complerer:</p><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#18181b" style="background-color:#18181b !important;border:1px solid #27272a;border-radius:12px;"><tr><td align="center" bgcolor="#18181b" style="background-color:#18181b !important;padding:24px;"><span style="font-size:36px;font-weight:700;letter-spacing:10px;color:#34d399 !important;">{{code}}</span></td></tr></table><p style="color:#71717a !important;font-size:12px;line-height:1.6;margin:16px 0 32px;">This code expires in 10 minutes. If you did not request this, please ignore this email.</p></td></tr><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:16px 32px 40px;border-top:1px solid #1c1c1f;"><p style="color:#3f3f46 !important;font-size:11px;margin:0;">Complerer · Compliance Platform</p></td></tr></table></td></tr></table>',
  updated_at = datetime('now')
WHERE slug = 'otp-verification';

UPDATE email_templates SET
  body_html = '<table width="100%" cellpadding="0" cellspacing="0" bgcolor="#09090b" style="background-color:#09090b !important;"><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:40px 20px;font-family:''Red Hat Display'',Arial,sans-serif;"><table cellpadding="0" cellspacing="0" bgcolor="#09090b" style="width:100%;max-width:480px;background-color:#09090b !important;border-radius:16px;"><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:40px 32px 24px;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="28" /></td></tr><tr><td bgcolor="#09090b" style="background-color:#09090b !important;padding:0 32px;"><h2 style="color:#fafafa !important;font-size:20px;font-weight:700;margin:0 0 8px;">You''ve been invited</h2><p style="color:#a1a1aa !important;font-size:14px;line-height:1.6;margin:0 0 8px;">You''ve been invited to join <strong style="color:#fafafa !important;">{{workspaceName}}</strong> on Complerer as a <strong style="color:#fafafa !important;">{{role}}</strong>.</p><p style="color:#a1a1aa !important;font-size:14px;line-height:1.6;margin:0 0 32px;">Sign in with this email address to accept and get started.</p><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding-bottom:16px;"><a href="{{loginUrl}}" style="display:inline-block;background-color:#34d399 !important;color:#09090b !important;font-weight:700;padding:14px 36px;border-radius:12px;text-decoration:none;font-size:14px;">Accept Invitation</a></td></tr></table><p style="color:#71717a !important;font-size:12px;text-align:center;margin:0 0 32px;">This invitation expires in 7 days.</p></td></tr><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:16px 32px 40px;border-top:1px solid #1c1c1f;"><p style="color:#3f3f46 !important;font-size:11px;margin:0;">Complerer · Compliance Platform</p></td></tr></table></td></tr></table>',
  updated_at = datetime('now')
WHERE slug = 'workspace-invitation';

UPDATE email_templates SET
  body_html = '<table width="100%" cellpadding="0" cellspacing="0" bgcolor="#09090b" style="background-color:#09090b !important;"><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:40px 20px;font-family:''Red Hat Display'',Arial,sans-serif;"><table cellpadding="0" cellspacing="0" bgcolor="#09090b" style="width:100%;max-width:480px;background-color:#09090b !important;border-radius:16px;"><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:40px 32px 24px;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="28" /></td></tr><tr><td bgcolor="#09090b" style="background-color:#09090b !important;padding:0 32px;"><h2 style="color:#fafafa !important;font-size:20px;font-weight:700;margin:0 0 8px;">Welcome to {{workspaceName}}</h2><p style="color:#a1a1aa !important;font-size:14px;line-height:1.6;margin:0 0 32px;">Your invitation request has been approved. You can now sign in and access the workspace.</p><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding-bottom:32px;"><a href="{{loginUrl}}" style="display:inline-block;background-color:#34d399 !important;color:#09090b !important;font-weight:700;padding:14px 36px;border-radius:12px;text-decoration:none;font-size:14px;">Sign In to Complerer</a></td></tr></table></td></tr><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:16px 32px 40px;border-top:1px solid #1c1c1f;"><p style="color:#3f3f46 !important;font-size:11px;margin:0;">Complerer · Compliance Platform</p></td></tr></table></td></tr></table>',
  updated_at = datetime('now')
WHERE slug = 'invitation-approved';

UPDATE email_templates SET
  body_html = '<table width="100%" cellpadding="0" cellspacing="0" bgcolor="#09090b" style="background-color:#09090b !important;"><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:40px 20px;font-family:''Red Hat Display'',Arial,sans-serif;"><table cellpadding="0" cellspacing="0" bgcolor="#09090b" style="width:100%;max-width:480px;background-color:#09090b !important;border-radius:16px;"><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:40px 32px 24px;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="28" /></td></tr><tr><td bgcolor="#09090b" style="background-color:#09090b !important;padding:0 32px;"><h2 style="color:#fafafa !important;font-size:20px;font-weight:700;margin:0 0 8px;">Request not approved</h2><p style="color:#a1a1aa !important;font-size:14px;line-height:1.6;margin:0 0 12px;">Unfortunately, your request to join <strong style="color:#fafafa !important;">{{workspaceName}}</strong> was not approved at this time.</p><p style="color:#a1a1aa !important;font-size:14px;line-height:1.6;margin:0 0 32px;">Please contact a workspace administrator for more information.</p></td></tr><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:16px 32px 40px;border-top:1px solid #1c1c1f;"><p style="color:#3f3f46 !important;font-size:11px;margin:0;">Complerer · Compliance Platform</p></td></tr></table></td></tr></table>',
  updated_at = datetime('now')
WHERE slug = 'invitation-rejected';

UPDATE email_templates SET
  body_html = '<table width="100%" cellpadding="0" cellspacing="0" bgcolor="#09090b" style="background-color:#09090b !important;"><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:40px 20px;font-family:''Red Hat Display'',Arial,sans-serif;"><table cellpadding="0" cellspacing="0" bgcolor="#09090b" style="width:100%;max-width:480px;background-color:#09090b !important;border-radius:16px;"><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:40px 32px 24px;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="28" /></td></tr><tr><td bgcolor="#09090b" style="background-color:#09090b !important;padding:0 32px;"><h2 style="color:#fafafa !important;font-size:20px;font-weight:700;margin:0 0 8px;">New join request</h2><p style="color:#a1a1aa !important;font-size:14px;line-height:1.6;margin:0 0 16px;"><strong style="color:#fafafa !important;">{{userName}}</strong> wants to join <strong style="color:#fafafa !important;">{{workspaceName}}</strong>.</p><table width="100%" cellpadding="0" cellspacing="0"><tr><td style="padding-bottom:28px;"><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#18181b" style="background-color:#18181b !important;border:1px solid #27272a;border-radius:10px;"><tr><td bgcolor="#18181b" style="background-color:#18181b !important;padding:14px 16px;"><p style="color:#71717a !important;font-size:11px;margin:0 0 4px;text-transform:uppercase;letter-spacing:0.5px;">Email</p><p style="color:#fafafa !important;font-size:14px;font-weight:600;margin:0;">{{userEmail}}</p></td></tr></table></td></tr><tr><td align="center" style="padding-bottom:32px;"><a href="{{settingsUrl}}" style="display:inline-block;background-color:#34d399 !important;color:#09090b !important;font-weight:700;padding:14px 36px;border-radius:12px;text-decoration:none;font-size:14px;">Review Request</a></td></tr></table></td></tr><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:16px 32px 40px;border-top:1px solid #1c1c1f;"><p style="color:#3f3f46 !important;font-size:11px;margin:0;">Complerer · Compliance Platform</p></td></tr></table></td></tr></table>',
  updated_at = datetime('now')
WHERE slug = 'new-invitation-request';

UPDATE email_templates SET
  body_html = '<table width="100%" cellpadding="0" cellspacing="0" bgcolor="#09090b" style="background-color:#09090b !important;"><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:40px 20px;font-family:''Red Hat Display'',Arial,sans-serif;"><table cellpadding="0" cellspacing="0" bgcolor="#09090b" style="width:100%;max-width:480px;background-color:#09090b !important;border-radius:16px;"><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:40px 32px 24px;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="28" /></td></tr><tr><td bgcolor="#09090b" style="background-color:#09090b !important;padding:0 32px;"><h2 style="color:#fafafa !important;font-size:20px;font-weight:700;margin:0 0 8px;">{{alertTitle}}</h2><p style="color:#a1a1aa !important;font-size:14px;line-height:1.6;margin:0 0 20px;">{{alertMessage}}</p><table width="100%" cellpadding="0" cellspacing="0"><tr><td style="padding-bottom:28px;"><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#18181b" style="background-color:#18181b !important;border:1px solid #27272a;border-radius:10px;"><tr><td bgcolor="#18181b" style="background-color:#18181b !important;padding:14px 16px;"><p style="color:#71717a !important;font-size:11px;margin:0 0 6px;">Severity</p><p style="font-size:14px;font-weight:700;color:{{severityColor}};margin:0 0 12px;">{{severity}}</p><p style="color:#71717a !important;font-size:11px;margin:0 0 4px;">Framework</p><p style="color:#fafafa !important;font-size:14px;margin:0;">{{framework}}</p></td></tr></table></td></tr><tr><td align="center" style="padding-bottom:32px;"><a href="{{dashboardUrl}}" style="display:inline-block;background-color:#34d399 !important;color:#09090b !important;font-weight:700;padding:14px 36px;border-radius:12px;text-decoration:none;font-size:14px;">View Dashboard</a></td></tr></table></td></tr><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:16px 32px 40px;border-top:1px solid #1c1c1f;"><p style="color:#3f3f46 !important;font-size:11px;margin:0;">Complerer · Compliance Platform</p></td></tr></table></td></tr></table>',
  updated_at = datetime('now')
WHERE slug = 'compliance-alert';

UPDATE email_templates SET
  body_html = '<table width="100%" cellpadding="0" cellspacing="0" bgcolor="#09090b" style="background-color:#09090b !important;"><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:40px 20px;font-family:''Red Hat Display'',Arial,sans-serif;"><table cellpadding="0" cellspacing="0" bgcolor="#09090b" style="width:100%;max-width:480px;background-color:#09090b !important;border-radius:16px;"><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:40px 32px 24px;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="28" /></td></tr><tr><td bgcolor="#09090b" style="background-color:#09090b !important;padding:0 32px;"><h2 style="color:#fafafa !important;font-size:20px;font-weight:700;margin:0 0 8px;">Evidence expiring soon</h2><p style="color:#a1a1aa !important;font-size:14px;line-height:1.6;margin:0 0 20px;">The following evidence will expire on <strong style="color:#fafafa !important;">{{expiresAt}}</strong>:</p><table width="100%" cellpadding="0" cellspacing="0"><tr><td style="padding-bottom:28px;"><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#18181b" style="background-color:#18181b !important;border:1px solid #27272a;border-radius:10px;"><tr><td bgcolor="#18181b" style="background-color:#18181b !important;padding:14px 16px;"><p style="color:#fafafa !important;font-weight:700;font-size:14px;margin:0 0 4px;">{{evidenceTitle}}</p><p style="color:#71717a !important;font-size:12px;margin:0;">Linked to {{controlCount}} controls</p></td></tr></table></td></tr><tr><td align="center" style="padding-bottom:32px;"><a href="{{evidenceUrl}}" style="display:inline-block;background-color:#34d399 !important;color:#09090b !important;font-weight:700;padding:14px 36px;border-radius:12px;text-decoration:none;font-size:14px;">Update Evidence</a></td></tr></table></td></tr><tr><td align="center" bgcolor="#09090b" style="background-color:#09090b !important;padding:16px 32px 40px;border-top:1px solid #1c1c1f;"><p style="color:#3f3f46 !important;font-size:11px;margin:0;">Complerer · Compliance Platform</p></td></tr></table></td></tr></table>',
  updated_at = datetime('now')
WHERE slug = 'evidence-expiring';
