-- Gmail dark mode inverts the dark header (#09090b) to white.
-- Fix: add a targeted <style> block using the "u+.body" selector hack —
-- a CSS selector that ONLY matches inside Gmail's rendering context.
-- Only the header and green bar are targeted; the white body is left alone
-- to adapt naturally (which already works).

UPDATE email_templates SET
  body_html = '<style>u+.body .eh{background-color:#09090b !important;}u+.body .eb{background-color:#34d399 !important;}</style><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#f4f4f5" style="background-color:#f4f4f5;"><tr><td align="center" style="padding:40px 16px;font-family:''Red Hat Display'',Arial,sans-serif;"><table cellpadding="0" cellspacing="0" style="width:100%;max-width:480px;"><tr><td class="eh" align="center" bgcolor="#09090b" style="background-color:#09090b;padding:28px 32px;border-radius:12px 12px 0 0;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="26" /></td></tr><tr><td class="eb" bgcolor="#34d399" style="background-color:#34d399;height:4px;font-size:0;line-height:0;">&nbsp;</td></tr><tr><td bgcolor="#ffffff" style="background-color:#ffffff;padding:32px 32px 24px;"><h2 style="color:#18181b;font-size:20px;font-weight:700;margin:0 0 8px;line-height:1.3;">Verify your email</h2><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 24px;">Enter this code to sign in to Complerer:</p><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#f4f4f5" style="background-color:#f4f4f5;border:1px solid #e4e4e7;border-radius:8px;"><tr><td align="center" style="padding:20px 16px;"><span style="font-size:32px;font-weight:700;letter-spacing:10px;color:#09090b;font-family:''Red Hat Display'',monospace,Arial;">{{code}}</span></td></tr></table><p style="color:#71717a;font-size:12px;line-height:1.6;margin:16px 0 0;">This code expires in 10 minutes. If you did not request this, please ignore this email.</p></td></tr><tr><td bgcolor="#fafafa" style="background-color:#fafafa;padding:16px 32px 20px;border-top:1px solid #e4e4e7;border-radius:0 0 12px 12px;"><p style="color:#a1a1aa;font-size:11px;text-align:center;margin:0;">Complerer · Compliance Platform</p></td></tr></table></td></tr></table>',
  updated_at = datetime('now')
WHERE slug = 'otp-verification';

UPDATE email_templates SET
  body_html = '<style>u+.body .eh{background-color:#09090b !important;}u+.body .eb{background-color:#34d399 !important;}</style><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#f4f4f5" style="background-color:#f4f4f5;"><tr><td align="center" style="padding:40px 16px;font-family:''Red Hat Display'',Arial,sans-serif;"><table cellpadding="0" cellspacing="0" style="width:100%;max-width:480px;"><tr><td class="eh" align="center" bgcolor="#09090b" style="background-color:#09090b;padding:28px 32px;border-radius:12px 12px 0 0;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="26" /></td></tr><tr><td class="eb" bgcolor="#34d399" style="background-color:#34d399;height:4px;font-size:0;line-height:0;">&nbsp;</td></tr><tr><td bgcolor="#ffffff" style="background-color:#ffffff;padding:32px 32px 8px;"><h2 style="color:#18181b;font-size:20px;font-weight:700;margin:0 0 8px;line-height:1.3;">You''ve been invited</h2><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 6px;">You''ve been invited to join <strong style="color:#18181b;">{{workspaceName}}</strong> on Complerer as a <strong style="color:#18181b;">{{role}}</strong>.</p><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 0;">Sign in with this email address to accept and get started.</p><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:28px 0 8px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" bgcolor="#34d399" style="background-color:#34d399;border-radius:8px;"><a href="{{loginUrl}}" style="display:inline-block;padding:13px 32px;font-size:14px;font-weight:700;color:#09090b;text-decoration:none;font-family:''Red Hat Display'',Arial,sans-serif;">Accept Invitation</a></td></tr></table></td></tr></table><p style="color:#a1a1aa;font-size:12px;text-align:center;margin:0 0 28px;">This invitation expires in 7 days.</p></td></tr><tr><td bgcolor="#fafafa" style="background-color:#fafafa;padding:16px 32px 20px;border-top:1px solid #e4e4e7;border-radius:0 0 12px 12px;"><p style="color:#a1a1aa;font-size:11px;text-align:center;margin:0;">Complerer · Compliance Platform</p></td></tr></table></td></tr></table>',
  updated_at = datetime('now')
WHERE slug = 'workspace-invitation';

UPDATE email_templates SET
  body_html = '<style>u+.body .eh{background-color:#09090b !important;}u+.body .eb{background-color:#34d399 !important;}</style><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#f4f4f5" style="background-color:#f4f4f5;"><tr><td align="center" style="padding:40px 16px;font-family:''Red Hat Display'',Arial,sans-serif;"><table cellpadding="0" cellspacing="0" style="width:100%;max-width:480px;"><tr><td class="eh" align="center" bgcolor="#09090b" style="background-color:#09090b;padding:28px 32px;border-radius:12px 12px 0 0;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="26" /></td></tr><tr><td class="eb" bgcolor="#34d399" style="background-color:#34d399;height:4px;font-size:0;line-height:0;">&nbsp;</td></tr><tr><td bgcolor="#ffffff" style="background-color:#ffffff;padding:32px 32px 8px;"><h2 style="color:#18181b;font-size:20px;font-weight:700;margin:0 0 8px;line-height:1.3;">Welcome to {{workspaceName}}</h2><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 0;">Your invitation has been approved. You can now sign in and start collaborating.</p><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:28px 0 28px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" bgcolor="#34d399" style="background-color:#34d399;border-radius:8px;"><a href="{{loginUrl}}" style="display:inline-block;padding:13px 32px;font-size:14px;font-weight:700;color:#09090b;text-decoration:none;font-family:''Red Hat Display'',Arial,sans-serif;">Sign In to Complerer</a></td></tr></table></td></tr></table></td></tr><tr><td bgcolor="#fafafa" style="background-color:#fafafa;padding:16px 32px 20px;border-top:1px solid #e4e4e7;border-radius:0 0 12px 12px;"><p style="color:#a1a1aa;font-size:11px;text-align:center;margin:0;">Complerer · Compliance Platform</p></td></tr></table></td></tr></table>',
  updated_at = datetime('now')
WHERE slug = 'invitation-approved';

UPDATE email_templates SET
  body_html = '<style>u+.body .eh{background-color:#09090b !important;}u+.body .eb{background-color:#34d399 !important;}</style><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#f4f4f5" style="background-color:#f4f4f5;"><tr><td align="center" style="padding:40px 16px;font-family:''Red Hat Display'',Arial,sans-serif;"><table cellpadding="0" cellspacing="0" style="width:100%;max-width:480px;"><tr><td class="eh" align="center" bgcolor="#09090b" style="background-color:#09090b;padding:28px 32px;border-radius:12px 12px 0 0;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="26" /></td></tr><tr><td class="eb" bgcolor="#34d399" style="background-color:#34d399;height:4px;font-size:0;line-height:0;">&nbsp;</td></tr><tr><td bgcolor="#ffffff" style="background-color:#ffffff;padding:32px 32px 32px;"><h2 style="color:#18181b;font-size:20px;font-weight:700;margin:0 0 8px;line-height:1.3;">Request not approved</h2><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 10px;">Unfortunately, your request to join <strong style="color:#18181b;">{{workspaceName}}</strong> was not approved at this time.</p><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0;">Please contact a workspace administrator if you think this was a mistake.</p></td></tr><tr><td bgcolor="#fafafa" style="background-color:#fafafa;padding:16px 32px 20px;border-top:1px solid #e4e4e7;border-radius:0 0 12px 12px;"><p style="color:#a1a1aa;font-size:11px;text-align:center;margin:0;">Complerer · Compliance Platform</p></td></tr></table></td></tr></table>',
  updated_at = datetime('now')
WHERE slug = 'invitation-rejected';

UPDATE email_templates SET
  body_html = '<style>u+.body .eh{background-color:#09090b !important;}u+.body .eb{background-color:#34d399 !important;}</style><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#f4f4f5" style="background-color:#f4f4f5;"><tr><td align="center" style="padding:40px 16px;font-family:''Red Hat Display'',Arial,sans-serif;"><table cellpadding="0" cellspacing="0" style="width:100%;max-width:480px;"><tr><td class="eh" align="center" bgcolor="#09090b" style="background-color:#09090b;padding:28px 32px;border-radius:12px 12px 0 0;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="26" /></td></tr><tr><td class="eb" bgcolor="#34d399" style="background-color:#34d399;height:4px;font-size:0;line-height:0;">&nbsp;</td></tr><tr><td bgcolor="#ffffff" style="background-color:#ffffff;padding:32px 32px 8px;"><h2 style="color:#18181b;font-size:20px;font-weight:700;margin:0 0 8px;line-height:1.3;">New join request</h2><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 20px;"><strong style="color:#18181b;">{{userName}}</strong> has requested to join <strong style="color:#18181b;">{{workspaceName}}</strong>.</p><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#f4f4f5" style="background-color:#f4f4f5;border:1px solid #e4e4e7;border-radius:8px;"><tr><td style="padding:14px 16px;"><p style="color:#71717a;font-size:11px;text-transform:uppercase;letter-spacing:0.6px;margin:0 0 3px;">Email address</p><p style="color:#18181b;font-size:14px;font-weight:600;margin:0;">{{userEmail}}</p></td></tr></table><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px 0 28px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" bgcolor="#34d399" style="background-color:#34d399;border-radius:8px;"><a href="{{settingsUrl}}" style="display:inline-block;padding:13px 32px;font-size:14px;font-weight:700;color:#09090b;text-decoration:none;font-family:''Red Hat Display'',Arial,sans-serif;">Review Request</a></td></tr></table></td></tr></table></td></tr><tr><td bgcolor="#fafafa" style="background-color:#fafafa;padding:16px 32px 20px;border-top:1px solid #e4e4e7;border-radius:0 0 12px 12px;"><p style="color:#a1a1aa;font-size:11px;text-align:center;margin:0;">Complerer · Compliance Platform</p></td></tr></table></td></tr></table>',
  updated_at = datetime('now')
WHERE slug = 'new-invitation-request';

UPDATE email_templates SET
  body_html = '<style>u+.body .eh{background-color:#09090b !important;}u+.body .eb{background-color:#34d399 !important;}</style><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#f4f4f5" style="background-color:#f4f4f5;"><tr><td align="center" style="padding:40px 16px;font-family:''Red Hat Display'',Arial,sans-serif;"><table cellpadding="0" cellspacing="0" style="width:100%;max-width:480px;"><tr><td class="eh" align="center" bgcolor="#09090b" style="background-color:#09090b;padding:28px 32px;border-radius:12px 12px 0 0;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="26" /></td></tr><tr><td class="eb" bgcolor="#34d399" style="background-color:#34d399;height:4px;font-size:0;line-height:0;">&nbsp;</td></tr><tr><td bgcolor="#ffffff" style="background-color:#ffffff;padding:32px 32px 8px;"><h2 style="color:#18181b;font-size:20px;font-weight:700;margin:0 0 8px;line-height:1.3;">{{alertTitle}}</h2><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 20px;">{{alertMessage}}</p><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#f4f4f5" style="background-color:#f4f4f5;border:1px solid #e4e4e7;border-radius:8px;"><tr><td style="padding:14px 16px;"><p style="color:#71717a;font-size:11px;text-transform:uppercase;letter-spacing:0.6px;margin:0 0 3px;">Severity</p><p style="font-size:14px;font-weight:700;color:{{severityColor}};margin:0 0 12px;">{{severity}}</p><p style="color:#71717a;font-size:11px;text-transform:uppercase;letter-spacing:0.6px;margin:0 0 3px;">Framework</p><p style="color:#18181b;font-size:14px;font-weight:600;margin:0;">{{framework}}</p></td></tr></table><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px 0 28px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" bgcolor="#34d399" style="background-color:#34d399;border-radius:8px;"><a href="{{dashboardUrl}}" style="display:inline-block;padding:13px 32px;font-size:14px;font-weight:700;color:#09090b;text-decoration:none;font-family:''Red Hat Display'',Arial,sans-serif;">View Dashboard</a></td></tr></table></td></tr></table></td></tr><tr><td bgcolor="#fafafa" style="background-color:#fafafa;padding:16px 32px 20px;border-top:1px solid #e4e4e7;border-radius:0 0 12px 12px;"><p style="color:#a1a1aa;font-size:11px;text-align:center;margin:0;">Complerer · Compliance Platform</p></td></tr></table></td></tr></table>',
  updated_at = datetime('now')
WHERE slug = 'compliance-alert';

UPDATE email_templates SET
  body_html = '<style>u+.body .eh{background-color:#09090b !important;}u+.body .eb{background-color:#34d399 !important;}</style><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#f4f4f5" style="background-color:#f4f4f5;"><tr><td align="center" style="padding:40px 16px;font-family:''Red Hat Display'',Arial,sans-serif;"><table cellpadding="0" cellspacing="0" style="width:100%;max-width:480px;"><tr><td class="eh" align="center" bgcolor="#09090b" style="background-color:#09090b;padding:28px 32px;border-radius:12px 12px 0 0;"><img src="https://dash.complerer.com/logo-white.png" alt="Complerer" height="26" /></td></tr><tr><td class="eb" bgcolor="#34d399" style="background-color:#34d399;height:4px;font-size:0;line-height:0;">&nbsp;</td></tr><tr><td bgcolor="#ffffff" style="background-color:#ffffff;padding:32px 32px 8px;"><h2 style="color:#18181b;font-size:20px;font-weight:700;margin:0 0 8px;line-height:1.3;">Evidence expiring soon</h2><p style="color:#52525b;font-size:14px;line-height:1.6;margin:0 0 20px;">The following evidence will expire on <strong style="color:#18181b;">{{expiresAt}}</strong> and needs to be renewed:</p><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#f4f4f5" style="background-color:#f4f4f5;border:1px solid #e4e4e7;border-radius:8px;"><tr><td style="padding:14px 16px;"><p style="color:#18181b;font-size:14px;font-weight:700;margin:0 0 4px;">{{evidenceTitle}}</p><p style="color:#71717a;font-size:12px;margin:0;">Linked to {{controlCount}} controls</p></td></tr></table><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px 0 28px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" bgcolor="#34d399" style="background-color:#34d399;border-radius:8px;"><a href="{{evidenceUrl}}" style="display:inline-block;padding:13px 32px;font-size:14px;font-weight:700;color:#09090b;text-decoration:none;font-family:''Red Hat Display'',Arial,sans-serif;">Update Evidence</a></td></tr></table></td></tr></table></td></tr><tr><td bgcolor="#fafafa" style="background-color:#fafafa;padding:16px 32px 20px;border-top:1px solid #e4e4e7;border-radius:0 0 12px 12px;"><p style="color:#a1a1aa;font-size:11px;text-align:center;margin:0;">Complerer · Compliance Platform</p></td></tr></table></td></tr></table>',
  updated_at = datetime('now')
WHERE slug = 'evidence-expiring';
