import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { HugeiconsIcon } from '@hugeicons/react';
import { Shield01Icon, CheckmarkCircle01Icon, Cancel01Icon, CrownIcon, UserGroupIcon, } from '@hugeicons/core-free-icons';
import { useAdminMembers, usePromoteMember, useDemoteMember } from '@/hooks/use-admin';
import { useAuth } from '@/hooks/use-auth';
export function AdminMembersPage() {
    const { data, isLoading } = useAdminMembers();
    const promote = usePromoteMember();
    const demote = useDemoteMember();
    const { user } = useAuth();
    const members = data?.members ?? [];
    const superAdmins = members.filter((m) => m.isSuperAdmin);
    const regularUsers = members.filter((m) => !m.isSuperAdmin);
    return (_jsxs("div", { className: "mx-auto w-full max-w-4xl space-y-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-zinc-100", children: "Super Admin Members" }), _jsx("p", { className: "mt-1 text-sm text-zinc-500", children: "Manage who has super admin access to the platform." })] }), isLoading ? (_jsx("div", { className: "flex h-40 items-center justify-center", children: _jsx("p", { className: "text-sm text-zinc-500", children: "Loading..." }) })) : (_jsxs(_Fragment, { children: [_jsxs("div", { className: "rounded-xl border border-zinc-800 bg-zinc-900 p-6", children: [_jsxs("div", { className: "mb-4 flex items-center gap-2", children: [_jsx(HugeiconsIcon, { icon: CrownIcon, size: 18, className: "text-amber-400" }), _jsx("h2", { className: "text-lg font-semibold text-zinc-100", children: "Super Admins" }), _jsx("span", { className: "rounded-full bg-amber-500/10 px-2 py-0.5 text-xs font-medium text-amber-400", children: superAdmins.length })] }), _jsx("div", { className: "space-y-2", children: superAdmins.map((member) => (_jsxs("div", { className: "flex items-center justify-between rounded-xl border border-zinc-800 bg-zinc-800/30 p-4", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-amber-400/20 to-amber-400/5", children: _jsx("span", { className: "text-sm font-semibold text-amber-400", children: member.name
                                                            .split(' ')
                                                            .map((w) => w[0])
                                                            .join('')
                                                            .slice(0, 2)
                                                            .toUpperCase() }) }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("p", { className: "text-sm font-medium text-zinc-100", children: member.name }), member.email === user?.email && (_jsx("span", { className: "rounded-md bg-zinc-800 px-1.5 py-0.5 text-[10px] text-zinc-500", children: "you" }))] }), _jsx("p", { className: "text-xs text-zinc-500", children: member.email })] })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "text-xs text-zinc-600", children: member.lastLoginAt
                                                        ? `Last login: ${new Date(member.lastLoginAt).toLocaleDateString()}`
                                                        : 'Never logged in' }), member.email !== user?.email && (_jsxs("button", { onClick: () => demote.mutate(member.id), disabled: demote.isPending, className: "flex items-center gap-1 rounded-lg border border-zinc-700 px-3 py-1.5 text-xs font-medium text-zinc-400 transition-colors hover:border-red-500/30 hover:bg-red-500/10 hover:text-red-400 disabled:opacity-50", children: [_jsx(HugeiconsIcon, { icon: Cancel01Icon, size: 12 }), "Remove admin"] }))] })] }, member.id))) })] }), _jsxs("div", { className: "rounded-xl border border-zinc-800 bg-zinc-900 p-6", children: [_jsxs("div", { className: "mb-4 flex items-center gap-2", children: [_jsx(HugeiconsIcon, { icon: UserGroupIcon, size: 18, className: "text-zinc-400" }), _jsx("h2", { className: "text-lg font-semibold text-zinc-100", children: "All Users" }), _jsx("span", { className: "rounded-full bg-zinc-800 px-2 py-0.5 text-xs font-medium text-zinc-400", children: regularUsers.length })] }), regularUsers.length === 0 ? (_jsxs("div", { className: "rounded-xl border border-dashed border-zinc-800 bg-zinc-800/20 py-8 text-center", children: [_jsx(HugeiconsIcon, { icon: CheckmarkCircle01Icon, size: 24, className: "mx-auto mb-2 text-zinc-600" }), _jsx("p", { className: "text-sm text-zinc-500", children: "All users are super admins" })] })) : (_jsx("div", { className: "space-y-2", children: regularUsers.map((member) => (_jsxs("div", { className: "flex items-center justify-between rounded-xl border border-zinc-800 bg-zinc-800/30 p-4", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "flex h-10 w-10 items-center justify-center rounded-full bg-zinc-800", children: _jsx("span", { className: "text-sm font-semibold text-zinc-400", children: member.name
                                                            .split(' ')
                                                            .map((w) => w[0])
                                                            .join('')
                                                            .slice(0, 2)
                                                            .toUpperCase() }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-zinc-100", children: member.name }), _jsx("p", { className: "text-xs text-zinc-500", children: member.email })] })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("span", { className: "text-xs text-zinc-600", children: ["Joined ", new Date(member.createdAt).toLocaleDateString()] }), _jsxs("button", { onClick: () => promote.mutate(member.id), disabled: promote.isPending, className: "flex items-center gap-1 rounded-lg bg-amber-500/10 px-3 py-1.5 text-xs font-medium text-amber-400 transition-colors hover:bg-amber-500/20 disabled:opacity-50", children: [_jsx(HugeiconsIcon, { icon: Shield01Icon, size: 12 }), "Make admin"] })] })] }, member.id))) }))] })] }))] }));
}
//# sourceMappingURL=members.js.map